### ISSUE TITLE
Display .tour_preview

### ISSUE THREAD

**Issue by kizoso** [Nevatrip/stub#3]
Вывести .tour_preview в результат фильтра, сейчас при попытке вывода показывает ошибку.

**Comment by Realetive** [comment]
1) модификатор `tour_preview`, очевидно, «отвечает» за представление блока `tour` в виде `preview`, т. е. модификатор в том случае будет `tour_view_preview`, потому что «видов» будет много ( `tour_view_preview`, `tour_view_full`, `tour_view_short` и т. д. );
2) Ошибка лишь в синтаксисе deps'ов:

```
[{
  shouldDeps: [
    {
      block: 'tour',
      mods: { preview: true }
    }
  ]
}]

```

**Comment by Realetive** [comment]
1) https://github.com/Nevatrip/stub/commit/87da172c55cacae598805bb92eaebc7f16821338
2) https://github.com/Nevatrip/stub/commit/32ac326ce7f3e34f488c5ec4ce793a83a0a1e9b0
